version: '3'

services:
  app-gateway:
    image: app-gate
    ports:
      - "16200:16200"
    build: ./app-gateway
    container_name: app-gate
  app-admin:
    image: app-admin
    ports:
      - "16201:16201"
    build: ./app-modules/app-admin
    container_name: app-admin