version: '3'

services:
  app-gateway:
    image: app-gateway
    ports:
      - "16200:16200"
    build: ./app-gateway
    container_name: app-gate
    networks:
      - common-net
  app-admin:
    image: app-admin
    ports:
      - "16201:16201"
    build: ./app-modules/app-admin
    container_name: app-admin
    networks:
      - common-net
  app-monitor:
    image: app-monitor
    ports:
      - "16202:16202"
    build: ./app-infrastructure/app-monitor
    container_name: app-monitor
    networks:
      - common-net
networks:
  common-net:
    external: true