spring:
  cloud:
    gateway:
      routes:
        - id: ace-auth
          uri: lb://ace-admin
          order: 8000
          predicates:
            - RequestBody=true
            - Path=/api/auth/**
          filters:
            - StripPrefix=2
        - id: ace-admin
          uri: lb://ace-admin
          order: 8001
          predicates:
            - RequestBody=true
            - Path=/api/admin/**
          filters:
            - StripPrefix=2